import houseimg1 from '../Images/Houses/1.jpeg';
import houseimg2 from '../Images/Houses/2.jpg';
import houseimg3 from '../Images/Houses/3.jpg';
import houseimg4 from '../Images/Houses/4.jpg';
import houseimg5 from '../Images/Houses/5.jpeg';
import houseimg6 from '../Images/Houses/6.jpg';
import houseimg7 from '../Images/Houses/7.jpg';
import appimg1 from '../Images/Aparts/1.jpg';
import appimg2 from '../Images/Aparts/2.jpg';
import appimg3 from '../Images/Aparts/3.jpg';
import appimg4 from '../Images/Aparts/4.jpg';
import appimg5 from '../Images/Aparts/5.jpeg';
import appimg6 from '../Images/Aparts/6.jpg';
import appimg7 from '../Images/Aparts/7.jpg';
import roomimg1 from '../Images/Rooms/1.webp';
import roomimg2 from '../Images/Rooms/2.webp';
import roomimg3 from '../Images/Rooms/3.jpg';
import roomimg4 from '../Images/Rooms/4.jpg';
import roomimg5 from '../Images/Rooms/5.jpg';
import roomimg6 from '../Images/Rooms/6.jpg';
import roomimg7 from '../Images/Rooms/7.jpg';

const cards = [
  {
    image: houseimg1,
    name: 'Palm Harbor',
    location: 'Mumbai, MH',
    date: new Date(2024, 0, 12),
    price: 40000,
    type: 'Villa',
    address: '2699 Green Valley, Mumbai, MH',
    beds: 3,
    bathroom: 2,
    length: 5,
    width: 7,
    popular: true,
  },
  {
    image: appimg1,
    name: 'Baverly SpringField',
    location: 'Nashik, MH',
    date: new Date(2024, 1, 15),
    price: 15000,
    type: 'Appartment',
    address: '2821 Lake Sevilla, Nashik, MH',
    beds: 4,
    bathroom: 2,
    length: 6,
    width: 7.5,
    popular: false,
  },
  {
    image: roomimg1,
    name: 'Faulkner Ave',
    location: 'Pune, MH',
    date: new Date(2024, 3, 1),
    price: 7000,
    type: 'Room',
    address: '909 Woodland St.Michigan, Pune, MH',
    beds: 4,
    bathroom: 3,
    length: 8,
    width: 10,
    popular: true,
  },
  //2nd set
  {
    image: houseimg2,
    name: 'Ashraya',
    location: 'Chennai, TN',
    date: new Date(2024, 2, 22),
    price: 30000,
    type: 'Villa',
    address: '2699,Green Valley, Chennai, TN',
    beds: 5,
    bathroom: 2,
    length: 5,
    width: 7,
    popular: false,
  },
  {
    image: appimg2,
    name: 'Greenacres',
    location: 'Mumbai, MH',
    date: new Date(2024, 1, 12),
    price: 21095,
    type: 'Appartment',
    address: '2699 Matunga, Mumbai, MH',
    beds: 3,
    bathroom: 2,
    length: 5,
    width: 7,
    popular: true,
  },
  {
    image: roomimg2,
    name: 'EcoStay',
    location: 'Pune, MH',
    date: new Date(2024, 1, 1),
    price: 4500,
    type: 'Room',
    address: '909 Hinjevadi, Pune, MH',
    beds: 4,
    bathroom: 3,
    length: 8,
    width: 10,
    popular: false,
  },
  //3rd set
  {
    image: appimg3,
    name: 'Peace apartments',
    location: 'Nashik, MH',
    date: new Date(2024, 0, 15),
    price: 17000,
    type: 'Appartment',
    address: '2821 Gangapur Road, Nashik, MH',
    beds: 4,
    bathroom: 2,
    length: 6,
    width: 7.5,
    popular: false,
  },
  {
    image: houseimg3,
    name: 'Hillside',
    location: 'Pune, MH',
    date: new Date(2024, 1, 22),
    price: 30000,
    type: 'Villa',
    address: '2699,Red Valley,Pune,MH',
    beds: 5,
    bathroom: 2,
    length: 5,
    width: 7,
    popular: false,
  },
  {
    image: roomimg3,
    name: 'Yashwini',
    location: 'Mumbai, MH',
    date: new Date(2024, 3, 1),
    price: 8800,
    type: 'Room',
    address: '909 Hinjevadi, Mumbai,MH',
    beds: 4,
    bathroom: 3,
    length: 8,
    width: 10,
    popular: true,
  },
  //4th set
  {
    image: appimg4,
    name: 'Meadow View',
    location: 'Mumbai, MH',
    date: new Date(2024, 4, 15),
    price: 16000,
    type: 'Appartment',
    address: '2821 Gangapur Road, Mumbai,MH',
    beds: 4,
    bathroom: 2,
    length: 6,
    width: 7.5,
    popular: false,
  },
  {
    image: houseimg4,
    name: 'Kalyan',
    location: 'Chennai, TN',
    date: new Date(2024, 1, 22),
    price: 60000,
    type: 'Villa',
    address: '2699,Red Valley,Chennai,TN',
    beds: 5,
    bathroom: 2,
    length: 5,
    width: 7,
    popular: true,
  },
  {
    image: roomimg4,
    name: 'Ambar',
    location: 'Pune, MH',
    date: new Date(2024, 0, 1),
    price: 9500,
    type: 'Room',
    address: '909 Hinjevadi, Pune,MH',
    beds: 4,
    bathroom: 3,
    length: 8,
    width: 10,
    popular: true,
  },
  //5th set
  {
    image: appimg5,
    name: 'Surf Rider',
    location: 'Pune, MH',
    date: new Date(2024, 4, 15),
    price: 22000,
    type: 'Appartment',
    address: '2821 Gangapur Road, Pune,MH',
    beds: 4,
    bathroom: 2,
    length: 6,
    width: 7.5,
    popular: false,
  },
  {
    image: houseimg5,
    name: 'Rockwell',
    location: 'Nashik, MH',
    date: new Date(2024, 2, 22),
    price: 50000,
    type: 'Villa',
    address: '2699,Red Valley,Nashik,MH',
    beds: 5,
    bathroom: 2,
    length: 5,
    width: 7,
    popular: true,
  },
  {
    image: roomimg5,
    name: 'Royal View',
    location: 'Chennai, TN',
    date: new Date(2024, 3, 1),
    price: 7500,
    type: 'Room',
    address: '909 Hinjevadi, Chennai,TN',
    beds: 4,
    bathroom: 3,
    length: 8,
    width: 10,
    popular: false,
  },
  //6th set
  {
    image: appimg6,
    name: 'Standard At Legacy',
    location: 'Nashik, MH',
    date: new Date(2024, 0, 15),
    price: 47000,
    type: 'Appartment',
    address: '2821 Gangapur Road, Nashik,MH',
    beds: 4,
    bathroom: 2,
    length: 6,
    width: 7.5,
    popular: false,
  },
  {
    image: houseimg6,
    name: 'Harvest Lofts',
    location: 'Mumbai, MH',
    date: new Date(2024, 2, 22),
    price: 70000,
    type: 'Villa',
    address: '2699,Red Valley,Mumbai,MH',
    beds: 5,
    bathroom: 2,
    length: 5,
    width: 7,
    popular: false,
  },
  {
    image: roomimg6,
    name: 'Ventura Ridge',
    location: 'Chennai, TN',
    date: new Date(2024, 0, 1),
    price: 24500,
    type: 'Room',
    address: '909 Hinjevadi, Chennai,TN',
    beds: 4,
    bathroom: 3,
    length: 8,
    width: 10,
    popular: true,
  },
  //7th set
  {
    image: appimg7,
    name: 'The Peak',
    location: 'Mumbai, MH',
    date: new Date(2024, 0, 15),
    price: 57000,
    type: 'Appartment',
    address: '2821 Gangapur Road, Mumbai,MH',
    beds: 4,
    bathroom: 2,
    length: 6,
    width: 7.5,
    popular: false,
  },
  {
    image: houseimg7,
    name: 'Gateway West Loop',
    location: 'Pune, MH',
    date: new Date(2024, 0, 22),
    price: 90000,
    type: 'Villa',
    address: '2699,Red Valley,Pune, MH',
    beds: 5,
    bathroom: 2,
    length: 5,
    width: 7,
    popular: true,
  },
  {
    image: roomimg7,
    name: 'Kingsford Peak',
    location: 'Nashik, MH',
    date: new Date(2024, 0, 1),
    price: 64500,
    type: 'Room',
    address: '909 Hinjevadi, Nashik,MH',
    beds: 4,
    bathroom: 3,
    length: 8,
    width: 10,
    popular: true,
  },
];
export default cards;
