const cards = [
  {
    name: 'Palm Harbor',
    location: 'New York,USA',
    date: new Date(2023, 0, 12),
    price: 2095,
    type: 'Houses',
    address: '2699 Green Valley,Highland,FL',
    beds: 3,
    bathroom: 2,
    length: 5,
    width: 7,
    popular: true,
  },
  {
    name: 'Baverly SpringField',
    location: 'Mumbai,IN',
    date: new Date(2023, 4, 15),
    price: 2700,
    type: 'Houses',
    address: '2821 Lake Sevilla,Palm Harbor,TX',
    beds: 4,
    bathroom: 2,
    length: 6,
    width: 7.5,
    popular: true,
  },
  {
    name: 'Faulkner Ave',
    location: 'Pune,IN',
    date: new Date(2023, 3, 1),
    price: 4500,
    type: 'Bunglow',
    address: '909 Woodland St.Michigan,IN',
    beds: 4,
    bathroom: 3,
    length: 8,
    width: 10,
    popular: true,
  },
  {
    name: 'Pethkar Plaza',
    location: 'Silicon Valley,USA',
    date: new Date(2023, 2, 22),
    price: 2000,
    type: 'Houses',
    address: '2699,Green Valley,Highland,FL',
    beds: 5,
    bathroom: 2,
    length: 5,
    width: 7,
    popular: true,
  },
  {
    name: 'Pethkar Plaza',
    location: 'Silicon Valley,USA',
    date: new Date(2023, 2, 22),
    price: 2000,
    type: 'Houses',
    address: '2699,Green Valley,Highland,FL',
    beds: 5,
    bathroom: 2,
    length: 5,
    width: 7,
    popular: true,
  },
  {
    name: 'Pethkar Plaza',
    location: 'Silicon Valley,USA',
    date: new Date(2023, 2, 22),
    price: 2000,
    type: 'Houses',
    address: '2699,Green Valley,Highland,FL',
    beds: 5,
    bathroom: 2,
    length: 5,
    width: 7,
    popular: true,
  },
  {
    name: 'Pethkar Plaza',
    location: 'Silicon Valley,USA',
    date: new Date(2023, 2, 22),
    price: 2000,
    type: 'Houses',
    address: '2699,Green Valley,Highland,FL',
    beds: 5,
    bathroom: 2,
    length: 5,
    width: 7,
    popular: true,
  },
  {
    name: 'Baverly SpringField',
    location: 'Mumbai,IN',
    date: new Date(2023, 4, 15),
    price: 2700,
    type: 'Houses',
    address: '2821 Lake Sevilla,Palm Harbor,TX',
    beds: 4,
    bathroom: 2,
    length: 6,
    width: 7.5,
    popular: true,
  },
  {
    name: 'Faulkner Ave',
    location: 'Pune,IN',
    date: new Date(2023, 3, 1),
    price: 4500,
    type: 'Bunglow',
    address: '909 Woodland St.Michigan,IN',
    beds: 4,
    bathroom: 3,
    length: 8,
    width: 10,
    popular: true,
  },
  {
    name: 'Pethkar Plaza',
    location: 'Silicon Valley,USA',
    date: new Date(2023, 2, 22),
    price: 2000,
    type: 'Houses',
    address: '2699,Green Valley,Highland,FL',
    beds: 5,
    bathroom: 2,
    length: 5,
    width: 7,
    popular: true,
  },
  {
    name: 'Pethkar Plaza',
    location: 'Silicon Valley,USA',
    date: new Date(2023, 2, 22),
    price: 2000,
    type: 'Houses',
    address: '2699,Green Valley,Highland,FL',
    beds: 5,
    bathroom: 2,
    length: 5,
    width: 7,
    popular: true,
  },
  {
    name: 'Pethkar Plaza',
    location: 'Silicon Valley,USA',
    date: new Date(2023, 2, 22),
    price: 2000,
    type: 'Houses',
    address: '2699,Green Valley,Highland,FL',
    beds: 5,
    bathroom: 2,
    length: 5,
    width: 7,
    popular: true,
  },
  {
    name: 'Pethkar Plaza',
    location: 'Silicon Valley,USA',
    date: new Date(2023, 2, 22),
    price: 2000,
    type: 'Houses',
    address: '2699,Green Valley,Highland,FL',
    beds: 5,
    bathroom: 2,
    length: 5,
    width: 7,
    popular: true,
  },
];
export default cards;
